"""table

Revision ID: 15532abbf093
Revises: 1fbfa43fdc29
Create Date: 2024-01-12 23:16:21.637846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15532abbf093'
down_revision = '1fbfa43fdc29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
